PROCEDURE alpha
  DIM CLS:BYTE
  DIM XCOR,YCOR,SIDE1,SIDE2,RADIUS,T,X,Y,Z:INTEGER
  DIM RESPONSE:STRING[1]
  CLS=12
  10 REPEAT
  PUT #1,CLS
  PRINT "Do you want to draw"
  PRINT "1) A rectangle"
  PRINT "2) A circle"
  PRINT "3) Quit"
  PRINT " -Press 1, 2 or 3...";
  GET #0,RESPONSE
  PRINT
  IF RESPONSE="1" THEN
  INPUT "Length of Side 1",SIDE1
  INPUT "Length of Side 2",SIDE2
  RUN GFX("MODE",0,0)
  RUN GFX("CLEAR")
  XCOR=10
  YCOR=10
  RUN GFX("LINE",XCOR,YCOR,XCOR+SIDE1,YCOR,1)
  RUN GFX("LINE",XCOR+SIDE1,YCOR,XCOR+SIDE1,YCOR+SIDE2,1)
  RUN GFX("LINE",XCOR+SIDE1,YCOR+SIDE2,XCOR,YCOR+SIDE2,1)
  RUN GFX("LINE",XCOR,YCOR+SIDE2,XCOR,YCOR,1)
  INPUT RESPONSE
  ELSE
  IF RESPONSE="2" THEN
  INPUT "What radius?...",RADIUS
  RUN GFX("MODE",0,1)
  RUN GFX("CLEAR")
  RUN GFX("CIRCLE",128,90,RADIUS)
  INPUT RESPONSE
  ENDIF
  ENDIF
  UNTIL RESPONSE<>"1" AND RESPONSE<>"2"
  RUN GFX("ALPHA")
  IF RESPONSE<>"3" THEN 10
