PROCEDURE saveWinInfo
  TYPE WININFO=FORMAT:BYTE; XSIZE:BYTE; YSIZE:BYTE; FOREGROUND:BYTE; BACKGROUND:BYTE; BORDER:BYTE
  PARAM info:WININFO
  RUN GFX2("WINFO", info.FORMAT, info.XSIZE, info.YSIZE, info.FOREGROUND, info.BACKGROUND, info.BORDER)
END

PROCEDURE restoreWinInfo
  TYPE WININFO=FORMAT:BYTE; XSIZE:BYTE; YSIZE:BYTE; FOREGROUND:BYTE; BACKGROUND:BYTE; BORDER:BYTE
  PARAM info:WININFO
  RUN GFX2("DWEND")
  RUN GFX2("DWSET", info.FORMAT, 0, 0, info.XSIZE, info.YSIZE, info.FOREGROUND, info.BACKGROUND, info.BORDER)
END

PROCEDURE main
  TYPE WININFO=FORMAT:BYTE; XSIZE:BYTE; YSIZE:BYTE; FOREGROUND:BYTE; BACKGROUND:BYTE; BORDER:BYTE
  DIM original:WININFO

  RUN saveWinInfo(original)

  PRINT "Format:     " + info.FORMAT
  PRINT "X Size:     " + info.XSIZE
  PRINT "Y Size:     " + info.YSIZE
  PRINT "Foreground: " + info.FOREGROUND
  PRINT "Background: " + info.BACKGROUND
  PRINT "Border:     " + info.BORDER

  RUN restoreWinInfo(original)
END
