PROCEDURE palette
  DIM T,K,J,X,Y,COLOR:INTEGER
  DIM RESPONSE:STRING[1]
  RUN GFX2("DWEND")
  RUN GFX2("DWSET",7,0,0,80,25,0,2,2)
  RUN GFX2("COLOR",3,2,2)
  COLOR=0
  RUN GFX2("CLEAR")
  RUN GFX2("CUROFF")
  FOR Y=0 TO 23 STEP 3
    RUN GFX2("COLOR",COLOR)
    RUN GFX2("BAR",0,Y,639,Y+3)
    COLOR=COLOR+1
    IF COLOR=2 THEN
      COLOR=COLOR+1
    ENDIF
  NEXT Y
  FOR Y=164 TO 185 STEP 3
    RUN GFX2("COLOR",COLOR)
    RUN GFX2("BAR",0,Y,639,Y+3)
    COLOR=COLOR+1
  NEXT Y
  COLOR=0
  FOR K=45 TO 170 STEP 48
    FOR T=100 TO 580 STEP 100
      RUN GFX2("COLOR",3)
      RUN GFX2("CIRCLE",T,K,30)
      RUN GFX2("COLOR",COLOR)
      RUN GFX2("FILL",T,K)
      COLOR=COLOR+1
      IF COLOR=2 THEN
        COLOR=COLOR+1
      ENDIF
    NEXT T
  NEXT K
  REPEAT
    X=RND(63)
    REPEAT
      Y=RND(16)+1
    UNTIL Y<>2
    RUN GFX2("PALETTE",Y,X)
    RUN INKEY(RESPONSE)
  UNTIL RESPONSE>""
  RUN GFX2("DEFCOL")
  RUN GFX2("CURON")
END
